export const getIdentifierSign = 'im/IM/getIdentifierSign' //获取签名
export const unreadMessageCount = 'message/sysMsg/selectUnreadMessage' //未读数量
export const caseList = 'client/case/selectMyCaseList' //案件列表
export const caseInfo = 'client/case/infoByCaseId' //案件详情
export const UnreadCasesList = 'message/sysMsg/selectUnreadCases' //未读案件
export const deliveryAddress = 'client/case/getDeliveryAddress' //送达地址
export const updateMsg = 'message/sysMsg/updateAllReadMessage' //更新案件消息数
export const allRelevant = 'client/case/getCaseAllRelevant';
export const Group = 'im/case/establishGroup' //创建群组
export const historyMsg = 'im/case/getHistoryMessage'; //历史消息